language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
r:
- 3.2
- 3.3
- 3.4
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --install-args=--build"
  - RGL_USE_NULL=TRUE
  - WARNINGS_ARE_ERRORS=1
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
before_install:
- ulimit -n 2048
- export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
- export PROJ_DIR=`basename $PWD`
- echo "travis_wait*\.log$" >> .Rbuildignore
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- v8_install ;
- dcmtk_install ;
- export rver=`r_version`; echo $rver ;
- export PACKAGE_NAME=`package_name`
- export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
- remove_neuroc_packages
- export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
- x=`export_clang_cxx`; eval ${x}
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
- echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
- clang_cxx
- export cmake_version="3.11"
- cmake --version
- x=`cmake_setup`; echo "${x}"; eval ${x};
- cmake --version
- export ants_user=neuroconductor
- echo "Installing Missing Deps ITKR"
- install_missing_remote_deps_all ${ants_user}/ITKR
- gh_binary_install ${ants_user}/ITKR ;
- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}"
  == "ANTsR" ]]; then Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type =
  'source', repo = 'http://cran.rstudio.com')" ; fi
- if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]]; then export
  R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ; export R_CHECK_ARGS="--no-vignettes
  ${R_CHECK_ARGS}" ; fi
- if [[ "${PACKAGE_NAME}" != "ITKR" ]]; then echo "Installing Missing Deps ANTsRCore"
  ; install_missing_remote_deps_all ${ants_user}/ANTsRCore; gh_binary_install_passive
  ${ants_user}/ANTsRCore ; fi
- if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; then echo
  "Installing Missing Deps ANTsR" ; install_missing_remote_deps_all ${ants_user}/ANTsR
  ; gh_binary_install_passive ${ants_user}/ANTsR ; fi
- if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; then export _R_CHECK_FORCE_SUGGESTS_=false
  ; fi
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- echo $PATH ;
- install_deps_no_suggests
- install_python_requirements ;
- R CMD javareconf ;
- travis_run_cache
script:
- x=`export_clang_cxx`; eval ${x}
- travis_wait 100 R CMD build ${R_BUILD_ARGS} .
- rm -f travis_wait*.log
- PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
- ls
- travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
- rm -f travis_wait*.log
- if [[ $CHECK_RET -ne 0 ]]; then echo "R CMD check failed"; check_fail; dump_logs;
  travis_terminate 1; fi
- check_warnings
after_success:
- dump_logs
after_failure:
- dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: vMjiGPGda1E9fLX+2XPG5DWOj7D9hABO2LzK52gYR/mb6jZiEVfsFcytGZyR9Gakfjvi5fsJM27YTES3FwFpZy0xd8AtBT19QoKBFxX5W56O6G3JtM5n+347Zdq6ioppYUqg8JaD1oFVtssNXybGT883vdRWRnAgdxwG0rH7nrYpQJHNTZ6Y8N9T8rqw5XKt1npJHCjl6xft/JB0moFj/Bak7nPGhznjfyAEotD3dH8VXWj1tPyV6CYYKkUVpfvgV6bw/hfzaYCu4k8sNrAbeLyxJuh4Rb+Flu655y+nT3e8b8BvIwwgCq4QSZvzUmd4l3C+8oEayup89Q1XRDHKyhLiM21opVe+MIMZQ2UfFgI2mWy2t9wVpXSf1UWbtVcUEguUN7bJpFVg5v77m7KKbftvyXHUctMZnPZmWrgiPUVZo1uKF+scdW8gbYwZ89v2NmYzpn7E1YGuT9U2OPtTzzVxlociqWAd51hbAUQ6XcVTbXyhb650v76d6GbnokfnEG+4ezV+3xJPGNQSP8/G2cRb8URIpE4UsriWccj35Dy4/ueKTk3BJjEsvz9JRZ9kWYD7NnsqUDjVvJXINIHgSpz30LzM05Pc4YT9xxqqHTaF7e6wxdjy5xa/50QQMfHbTvtNYEDbX45FgxE+h0rVXUbxhNH93wB1mku0kwTTGyQ=
after_deploy:
- if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}"
  != "ANTsRCore" ]]; then if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then
  Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ; fi fi
